src/components/pages/contributors/how-it-works/how-it-works.jsx, src/constants/links.js
This pull request updates the documentation links, remove the extra /docs preview in URL.
Related PR: https://github.com/novuhq/novu/pull/717
=> fix: update the documentation links

src/styles/global.css
issue #21 
I have changed main `novu.co` website's scrollbar and now it is looking exactly same with `docs.novu.co`
=> fix: (novu-website) scrollbar update

src/components/pages/contributor/achievements/achievements.jsx
This PR fixes wording on the individual contributor's page to avoid using two -ing verbs next to each other.
Thank you for helping growing Novu -> Thank you for **helping Novu grow**!
=> fix: fix wording on contributor page

src/components/pages/pricing/hero-with-cards/cloud/cloud.jsx, src/components/shared/tooltip/tooltip.jsx
At first look, everything looks right:
But let's scroll down, and we can see slider overlapping tooltip
=> Fix: prevent cloud pricing slider overlapping tooltip

src/components/pages/pricing/hero-with-cards/cloud/cloud.jsx, src/components/pages/pricing/pricing-table/data/pricing-plans.js, src/constants/links.js
This PR does three things:
1) Changes some of the language on the /pricing page
2) Updates the calendly meeting links in the links file, as well as the /pricing page to use hubspot meetings instead
3) Updates multiple UTM tags across the site
=> Pricing Language, Meeting links, and UTM tags

src/components/pages/pricing/faq/faq.jsx, src/components/pages/pricing/hero-with-cards/cloud/cloud.jsx
Made two minor tweaks to the pricing page:
1) Updated the FAQ to reflect the new higher event limit for the free tier. It was 10k, it is now 30k events/month.
2) Updated the tiered pricing to correct one of the tiers to the correct (and lower) price.
=> Pricing page tweaks

src/components/pages/home/languages/languages.jsx, src/pages/index.jsx
This PR removes default links at the `Languages` component
=> fix: remove default landing code block links

src/constants/links.js
fix the link until a further decision has been made on naming guides/howto/recipes
=> fix: revert link to guides/workflows/introduction

src/components/pages/home/code/code-with-tooltip/code-with-tooltip.jsx, src/components/pages/home/code/code.jsx
**What?**
* Fix the positioning of the code snippet background image
* Use consistent spacing for the tooltip code popover snippets
**Screens**
_Large_
_Medium_
_Small_
_Extra Small_
=> fix(components): styles for code snippet

src/components/pages/home/hero/hero.jsx, src/components/pages/home/skinny-cta/skinnycta.jsx, src/constants/links.js
Updated Hero text, moved several homepage CTAs to "Contact Us" instead of book a meeting.
=> chore: update hero and CTAs

src/components/pages/add-notifications/cta/cta.jsx, src/components/pages/content-management/cta/cta.jsx, src/components/pages/home/cta/cta.jsx, src/components/pages/improve-communication-experience/cta/cta.jsx, src/components/pages/multi-channel-notifications/cta/cta.jsx, src/components/pages/unified-platform/cta/cta.jsx, src/constants/links.js, src/pages/index.jsx, src/pages/usecases/add-notifications.jsx, src/pages/usecases/content-management.jsx, src/pages/usecases/improve-communication-experience.jsx, src/pages/usecases/multi-channel-notifications.jsx, src/pages/usecases/unified-platform.jsx
Moves meeting link from group-based to RR
Todo in the future:
- Make this a local redirect so we only edit it in one place.
- Separately build out two prod meeting request links: one round robin, and the other group-based
=> chore: update meeting link

src/components/pages/blog-post/table-of-contents/table-of-contents.jsx, src/components/shared/cookie-banner/cookie-banner.jsx, src/utils/get-react-content-with-lazy-blocks.jsx
This PR excludes symbols `?` and `!` from `id` for Table of Contents in Blog posts.
=> fix: exclude symbols from id

community-heroes-cache.json, src/api/hubspot.js, src/components/pages/add-notifications/related-content/data.js, src/components/pages/community/get-involved/get-involved.jsx, src/components/pages/content-management/related-content/data.js, src/components/pages/hacktoberfest/issues/issues.jsx, src/components/pages/home/reviews/reviews.css, src/components/pages/home/reviews/reviews.jsx, src/components/pages/improve-communication-experience/related-content/data.js, src/components/pages/pricing/faq/question/question.jsx, src/components/pages/timeline/timeline/timeline.css, src/components/pages/use-case/content/content.jsx, src/components/pages/use-case/workflow/workflow.jsx, src/components/shared/banner/banner.jsx, src/icons/review-arrow.inline.svg, src/pages/index.jsx, src/styles/remove-autocomplete-styles.css, src/templates/landing.jsx
[Preview](https://6724dddcf0924e00089e8631--novu-website.netlify.app/)
=> feat: remade tweet section

src/components/pages/pricing/pricing-table/data/pricing-plans.js
Added RPS from eng:
```
[ApiServiceLevelEnum.FREE]: {
[ApiRateLimitCategoryEnum.TRIGGER]: 60,
[ApiRateLimitCategoryEnum.CONFIGURATION]: 20,
[ApiRateLimitCategoryEnum.GLOBAL]: 30,
},
[ApiServiceLevelEnum.BUSINESS]: {
[ApiRateLimitCategoryEnum.TRIGGER]: 600,
[ApiRateLimitCategoryEnum.CONFIGURATION]: 200,
[ApiRateLimitCategoryEnum.GLOBAL]: 300,
},
[ApiServiceLevelEnum.ENTERPRISE]: {
[ApiRateLimitCategoryEnum.TRIGGER]: 6000,
[ApiRateLimitCategoryEnum.CONFIGURATION]: 2000,
[ApiRateLimitCategoryEnum.GLOBAL]: 3000,
},
```
=> Add RPS to `/pricing`

src/components/shared/reusable-sections/get-involved/get-involved.jsx, src/components/shared/reusable-sections/section-with-video/section-with-video.jsx, src/pages/landing/get-started.jsx, src/pages/landing/react-email-blocks.jsx
This PR brings reusable sections styles fix:
1. Get Involved reusable components section
⬇️
2. Video sections on landing pages
⬇️
[Preview](https://deploy-preview-293--novu-website.netlify.app/inbox/)
=> fix: reusable sections styles

src/pages/testpages/reusable-components-2.jsx, src/pages/testpages/reusable-components.jsx
This sets each component title to match the name of the component, which makes it far easier to find the right one and insert it during new page development.
=> chore: update section names in sample page

src/components/shared/reusable-sections/text-with-picture/text-with-picture.jsx, src/constants/menus.js, src/pages/framework.jsx, src/pages/usecases.jsx
**Description**
This PR brings fixes for 
- images on Use-cases page;
- link for header to use-cases page;
**Steps to test**
1. Open [the page](https://deploy-preview-315--novu-website.netlify.app/usecases)
2. Confirm that everything looks and works as expected
**Screenshots**
<details>
<summary>Header link issue</summary>
</details>
<details>
<summary>Use cases images issue</summary>
</details>
=> fix: use-cases images fix, header link

src/pages/index.jsx
This PR brings new heading for Inbox section on the main Page
[Preview](https://deploy-preview-326--novu-website.netlify.app/)
Before
After
=> feat: change inbox section heading on home page

src/pages/pricing.jsx
Under the Enterprise card on the pricing page, there’s a visible "<br />" tag.
=> Fix: Removed incorrectly rendered <br /> tag from the page.

gatsby-browser.js
Fix scroll-to-top issue on route change in Gatsby
Addresses an issue where `scroll-behavior: smooth` causes the scroll-to-top action to be interrupted during rehydration, due to layout shifts from dynamically loaded DOM elements
**Steps to check:**
1. Open preview: [Home page](https://deploy-preview-341--novu-website.netlify.app/), [URL with hash](https://deploy-preview-341--novu-website.netlify.app/landing/get-started/#video)
2. Make sure that everything looks and works as expected
=> fix: scroll-to-top issue on route change
