novuhq/website

src/components/pages/contributor/profile/profile.jsx
src/components/pages/contributors/achievments/item/item.jsx

This pull request adds a temporary fix for Contributors `avatars`.
**Steps to test**
1. Open [the page](https://websitemain13551-fixcontributors.gtsb.io/contributors/)
2. Confirm that everything looks and works as expected

fix: avatar of the Contributor's profile

---

src/constants/menus.js

fix: invalid property name

---

gatsby-config.js
package-lock.json
package.json

This pull request adds RSS file generation for the blog.
**Steps to test**
1. Open [the page](https://websitemain13551-blogrss.gtsb.io/blog/rss.xml)
2. Confirm that everything looks and works as expected

chore: add RSS file generation for the blog

---

src/constants/links.js
src/constants/menus.js

feat: add status page :sparkles:

---

src/components/pages/home/languages/languages.jsx

Whilst visiting your site I saw an extra U, so I removed it!
Have a nice day

fix: removed the extra U to UNIQUE_IDENTIFIER

---

src/constants/menus.js

Fix Website Footer Typo

---

src/components/shared/seo/seo.jsx
src/templates/contributor.jsx

Updated the og:image to use GitHub avatar instead of a local copy of the user's image
fixes #36

Fix og:image of contributors profile

---

src/components/pages/contributor/achievements/achievements.jsx
src/components/pages/contributors/achievements/constants/data.js

This PR brings medal descriptions for contributors page
[Contributors](https://clinquant-conkies-d7f938.netlify.app/contributors/)
[Contributor](https://clinquant-conkies-d7f938.netlify.app/contributors/Rutam21/)

feat: add medal descriptions

---

src/components/pages/contributor/achievements/achievements.jsx
src/templates/contributor.jsx

This PR update achievement data structure for contributor page – now the Date is separate from the WpAchievements object

feat: update userAchievement data structure

---

src/components/pages/home/community/community.jsx
src/pages/404.jsx

<details>
<summary>GitHub counter</summary>
before:
after:
</details>
<details>
<summary>Gatsby Head for the 404 page</summary>
before:
after:
</details>

chore: minor adjustments to SEO and styles

---

src/components/pages/contributor/achievements/share/share.jsx
src/components/pages/hacktoberfest/swag/swag.jsx
src/components/pages/podcast-detail/share-and-subscribe/share/share.jsx
src/components/shared/burger/burger.jsx
src/components/shared/link/link.jsx
src/components/shared/mobile-menu/mobile-menu.jsx
src/components/shared/subscribe/form/form.jsx
src/context/audio-player.jsx

**Overview**
This pull request adds an update that reduces the framer-motion bundle.

chore: reduction of the framer-motion bundle

---

src/constants/links.js
src/constants/menus.js

**Description**
This PR adds the DPA page

feat: add the DPA page

---

src/components/pages/home/languages/languages.jsx
src/constants/links.js

- Add Python, Kotlin, Go, Ruby, PHP & Curl code samples
- Add link to view SDKs

Add New SDKs & Code Samples

---

package-lock.json
package.json
src/components/shared/button/button.jsx
src/components/shared/cookie-banner/cookie-banner.jsx
src/components/shared/cookie-banner/index.js
src/components/shared/cookie-banner/settings/checkbox/checkbox.jsx
src/components/shared/cookie-banner/settings/checkbox/images/check.inline.svg
src/components/shared/cookie-banner/settings/checkbox/index.js
src/components/shared/cookie-banner/settings/index.js
src/components/shared/cookie-banner/settings/settings.jsx
src/components/shared/layout/layout.jsx
src/components/shared/link/link.jsx
src/components/shared/modal/modal.jsx

feat: add a cookie banner and its configuration

---

gatsby-config.js
package-lock.json
package.json
redirects.json
src/components/pages/home/community/community.jsx
src/components/pages/home/how-it-works/how-it-works.jsx
src/components/pages/polishing/content/content.jsx
src/components/pages/timeline/timeline/item/item.jsx
src/components/pages/timeline/timeline/timeline.jsx
src/constants/links.js
src/templates/blog.jsx

This pull request brings some seo optimization fixes:
1. add [robots.txt](https://deploy-preview-87--novu-website.netlify.app/robots.txt)
2. [sitemap](https://deploy-preview-87--novu-website.netlify.app/sitemap-index.xml)
3. add main `h1` heading for [blog](https://deploy-preview-87--novu-website.netlify.app/blog/), update redundant in article
4. fix 404 error links
5. remove redundant empty external links to dev.to from articles
6. add meta description for blog categories
7. clean up redundant categories from blog
8. add alt for some images
9. add redirect from [/podcast/](https://deploy-preview-87--novu-website.netlify.app/podcast/) to `/blog/podcast/`

feat: seo optimization

---

src/constants/links.js

Update links.js (Discord link)

Update links.js (Discord link)

---

CONTRIBUTING.md

resolves #61 
The PR adds a `Contributing.md` file since the project does not include one. The copy of the content was gotten from the **Novu** may repo as requested for in the issue

task: created Contribution.md

---

src/components/pages/hacktoberfest/global-events/global-events.jsx

Add RSVP links for three events and add timezone in table heading

Hacktoberfest 23

---

.gitignore
netlify.toml
netlify/functions/sheduled-deploy.js
package-lock.json
package.json

This pull request implements a cron job for redeployment every two hours within Netlify serverless functions.
TODO:

chore: add cron redeploy

---

src/components/shared/banner/banner.jsx
src/components/shared/link/link.jsx
src/components/shared/mobile-menu/mobile-menu.jsx

This pull request addresses a minor UI fix for the mobile menu. 
To verify the changes:
- Open the [preview](https://deploy-preview-114--novu-website.netlify.app/) on a mobile device or using the inspector.
- Ensure that everything appears and functions as intended.

chore: mobile menu fix

---

gatsby-node.js

This pull request solves leaderboard table bug

fix: hacktoberfest fetch filter

---

src/components/pages/hacktoberfest/global-events/global-events.jsx

feat: add reminder link

---

src/constants/links.js

I've updated all the broken links on our main https://novu.co/ web page.

Fix: Fixed all the broken links, update links.js [Ticket DVRL-54]

---

src/constants/links.js

Updated the link to the notification center docs.

Update links.js [ticket DVRL-54]

---

src/components/shared/floating-button/floating-button.jsx
src/components/shared/seo/seo.jsx
src/styles/global.css

This pull request brings HubSpot tracking code and chat functionality
**Steps to check**: 
- open [preview](https://deploy-preview-135--novu-website.netlify.app/) 
- make sure that tracking script loading successfully

feat: add chat script

---

src/components/pages/pricing/hero-with-cards/cloud/cloud.jsx
src/pages/pricing.jsx

This PR returns the slider to the [pricing](https://deploy-preview-144--novu-website.netlify.app/pricing/) page

feat: return of pricing slider

---

src/components/pages/pricing/hero-with-cards/cloud/cloud.jsx
src/components/pages/pricing/pricing-table/data/pricing-plans.js
src/components/shared/header/header.jsx
src/components/shared/layout/layout.jsx
src/constants/links.js
src/constants/menus.js

Made multiple updates site-wide
1) Removed Golden Kitty banner
2) Removed Hacktoberfest from the header and footer nav 
3) Added analytics to top bar Get Started button
4) Changed CTAs for Enterprise pricing plans on pricing page 
5) Made required link updates in links.js
6) Added links to a new contact us page for pricing

Analytics and Pricing experiment

---

src/components/pages/landing/features/features.jsx
src/components/pages/landing/hero/hero.jsx

This PR brings some fixes for landing page template

fix: features items spacing

---

src/components/pages/home/hero/hero.jsx
src/constants/links.js

Improving analytics by enabling flexible UTM link additions through a function.

docs(components): added link function

---

src/components/pages/pricing/hero-with-cards/cloud/cloud.jsx

Added tooling to make addition of UTM parameters easier at scale, also added said UTM parameters.

Updated analytics links

---

src/components/pages/pricing/hero-with-cards/cloud/cloud.jsx
src/components/pages/pricing/pricing-table/data/pricing-plans.js
src/components/pages/pricing/pricing-table/pricing-table.jsx
src/pages/pricing.jsx

Updated pricing page to change how we display cost

docs(components): pricing page tweak

---

src/components/shared/seo/seo.jsx

Adding CrazyEgg heat, scroll, and click analytics

docs(components): add crazyegg heatmapping

---

src/components/pages/home/languages/languages.jsx

https://docs.novu.co/workflows/notification-workflows#faqs
`WORKFLOW_TRIGGER_ID` and `WORKFLOW_TRIGGER_IDENTIFIER` are different thing

fix: update workflow trigger id to trigger identifier

---

src/utils/community-utils.js

**Description**
This pull request fix build errors

fix: fix community page build errors

---

src/constants/links.js
src/constants/menus.js

Removed Contributors from nav, added Community

fix(pages): correct nav link

---

src/components/pages/echo/code/code-with-tooltip/step-tooltip/step-tooltip.jsx
src/components/pages/echo/code/code.jsx
src/components/pages/echo/cta/cta.jsx
src/components/pages/echo/flexibility/flexibility.jsx
src/components/pages/echo/hero/hero.jsx
src/components/pages/echo/infrastructure/infrastructure.jsx
src/components/pages/echo/integration/integration.jsx
src/components/pages/echo/libraries/libraries.jsx
src/components/pages/echo/testimonials/testimonials.jsx
src/styles/container.css

This pull-request brings small fixes for echo page

fix: fixes after code review

---

src/components/shared/inkeep-widgets/inkeep-chat-button/inkeep-chat-button.jsx

This pull request fixes 'Ask AI' button position
Steps to check:
- open preview
- check that 'Ask AI' and up buttons are equidistant from the right side

fix: fix ask ai button position

---

src/components/pages/novu-framework/code/code.jsx
src/components/pages/novu-framework/cta/cta.jsx
src/components/pages/novu-framework/hero/hero.jsx
src/components/pages/novu-framework/inbox/inbox.jsx
src/components/pages/novu-framework/logos/logos.jsx

https://github.com/novuhq/website/assets/63902456/537127f2-3eab-4046-9e6d-b625e002a93c

feat: I've added changes to the home page draft

---

src/components/pages/content-management/cta/cta.jsx
src/components/pages/content-management/cta/images/background.svg
src/components/pages/content-management/cta/index.js
src/pages/usecases/content-management.jsx

https://github.com/novuhq/website/assets/63902456/e78cad0d-b49d-4088-8ff6-2f71e09ee561

feat: added new CTA section to the usecase page

---

src/components/pages/add-notifications/benefits/benefits.jsx
src/components/pages/add-notifications/features/features.jsx
src/components/pages/add-notifications/hero/hero.jsx
src/components/pages/add-notifications/painRestatement/painRestatement.jsx
src/pages/usecases/add-notifications.jsx

Updated use case page order and modified some content on add-notifications

feat(pages): updated use case page order

---

src/components/pages/echo/integration/integration.jsx
src/components/pages/novu-framework/hero/hero.jsx
src/components/pages/novu-framework/inbox/inbox.jsx
src/components/pages/novu-framework/infrastructure/infrastructure.jsx
src/pages/novu-framework.jsx

Updated text based on @ComBarnea feedback

fix(pages): applied feedback

---

src/components/shared/subscribe-form/subscribe-form.jsx

This pull request fixes subscription form error.

fix: fix subscription form error

---

src/components/pages/add-notifications/benefits/benefits.jsx
src/components/pages/add-notifications/features/features.jsx
src/components/pages/add-notifications/hero/hero.jsx
src/components/pages/add-notifications/painRestatement/painRestatement.jsx

Round one of use case updates.

feat(pages): update use case content

---

src/components/pages/novu-framework/code/code.jsx
src/components/pages/novu-framework/infrastructure/infrastructure.jsx
src/components/pages/novu-framework/integration/integration.jsx

Fixed a few typos, sharpened language

feat(pages): minor text updates

---

src/components/pages/content-management/benefits/benefits.jsx
src/components/pages/content-management/cta/cta.jsx
src/components/pages/content-management/features/features.jsx
src/components/pages/content-management/hero/hero.jsx
src/components/pages/content-management/painRestatement/painRestatement.jsx
src/components/pages/novu-framework/code/code.jsx
src/components/pages/novu-framework/infrastructure/infrastructure.jsx
src/components/pages/novu-framework/integration/integration.jsx

Update language use-case wide.

Justnems review content management

---

src/components/pages/add-notifications/cta/cta.jsx
src/components/pages/content-management/cta/cta.jsx
src/components/pages/echo/cta/cta.jsx
src/components/pages/echo/hero/hero.jsx
src/components/pages/improve-communication-experience/cta/cta.jsx
src/components/pages/multi-channel-notifications/cta/cta.jsx
src/components/pages/novu-framework/cta/cta.jsx
src/components/pages/novu-framework/hero/hero.jsx
src/components/pages/unified-platform/cta/cta.jsx

* Use new `npx novu dev` command on https://novu.co/novu-framework/ and other places

refactor: Update `npx novu dev` command

---

src/components/pages/add-notifications/cta/cta.jsx
src/components/pages/content-management/benefits/benefits.jsx
src/components/pages/content-management/cta/cta.jsx
src/components/pages/improve-communication-experience/benefits/benefits.jsx
src/components/pages/improve-communication-experience/cta/cta.jsx
src/components/pages/multi-channel-notifications/cta/cta.jsx
src/components/pages/unified-platform/benefits/benefits.jsx
src/components/pages/unified-platform/cta/cta.jsx
src/components/pages/unified-platform/features/features.jsx
src/components/pages/unified-platform/hero/hero.jsx
src/components/pages/unified-platform/painRestatement/painRestatement.jsx

Updated CTAs, and benefits site-wide.

CTA fixes, updated benefits

---

src/components/pages/novu-framework/cta/cta.jsx
src/components/pages/novu-framework/testimonials/testimonials.jsx

Added testimonials, updated CTA link

Justnems add testimonials

---

src/components/pages/novu-framework/code/code-with-tooltip/code-with-tooltip.jsx
src/components/pages/novu-framework/code/code.jsx
src/components/pages/novu-framework/code/create-custom-element/create-custom-element.jsx

**What?**
* Add new `@novu/framework` snippet for AI digest
* Fix the left padding functionality for hover snippets
https://deploy-preview-207--novu-website.netlify.app/novu-framework/
**Screenshot**

feat(components): updated code snippets for framework

---

src/constants/links.js

Replaced Ashby link with Teamtailor

fix: update careers page link

---

src/components/pages/home/flexibility/flexibility.jsx
src/components/pages/home/hero/hero.jsx
src/components/pages/home/inbox/inbox.jsx
src/components/pages/home/infrastructure/infrastructure.jsx
src/components/pages/home/libraries/libraries.jsx
src/components/pages/home/logos/logos.jsx
src/components/pages/home/reviews/reviews.jsx
src/components/pages/home/skinny-cta/skinnycta.jsx

This pull request brings small adaptive fixes for new main page.

fix: small adaptive fixes for main page

---

gatsby-node.js
src/constants/menus.js

We now have access to the contributors.novu.co endpoint, and have updated the SSL certificate.

feat: re-enable contributors sectiom

---

src/components/pages/home/reviews/reviews.jsx

Add back Guillermo from Vercel's tweet about Novu

chore: add back guillermo's review

---

src/components/shared/cookie-banner/cookie-banner.jsx

This pull request brings new position for cookie popup

feat: reposition cookie popup

---

src/components/pages/home/hero/hero.jsx

fix: update hero case

---

src/components/pages/home/hero/hero.jsx

This reverts commit 37580e14d172eeaaebaab6881de467eef08a60da.

Revert "fix: update NextJS case (#244)"

---

gatsby-node.js
src/components/shared/issues/issues.jsx
src/templates/community.jsx

This pull request returns integration with contributors API for `/community` and `/contributors` pages.
**Steps to test:**
- open previews - [community](https://deploy-preview-246--novu-website.netlify.app/community/) & [contributors](https://deploy-preview-246--novu-website.netlify.app/contributors/)
- check that everything works as expected

feat: return integration with contributors API

---

src/components/pages/add-notifications/cta/cta.jsx
src/components/pages/content-management/cta/cta.jsx
src/components/pages/home/cta/cta.jsx
src/components/pages/improve-communication-experience/cta/cta.jsx
src/components/pages/multi-channel-notifications/cta/cta.jsx
src/components/pages/unified-platform/cta/cta.jsx
src/constants/links.js

Updated the meeting URL site-wide to a new group event that includes both Ryan and Stephen.

Meeting booking URL update

---

src/components/pages/community/events/data.json

Update the community events page with office hours. This still needs to be populated with Youtube links once we have them. Waiting on final scheduling confirmation

fix: update office hours

---

src/constants/links.js
src/constants/menus.js
src/pages/inbox.jsx
src/pages/index.jsx

Update inbox links to function properly, and exposes the inbox feature page in the main nav menu

Inbox fixes

---

src/pages/inbox.jsx

Added a "your" when it was a "you".

fix: inbox typo

---

src/components/pages/home/hero/hero.jsx

"Robust and flexible notification building blocks."
"Open source JavaScript-native notifications framework for developers that makes it easy to build powerful notifications capabilities for your product teams."

chore: update homepage hero

---

src/components/shared/reusable-sections/section-with-form/index.js
src/components/shared/reusable-sections/section-with-form/section-with-form.jsx
src/hooks/use-hubspot-form.js
src/pages/testpages/reusable-components.jsx
src/styles/hubspot-form.css

This pull request brings section with form as a reusable section.
Preview - https://deploy-preview-267--novu-website.netlify.app/testpages/reusable-components/

feat: add section with form as a reusable section

---

src/pages/landing/get-started.jsx
src/pages/testpages/reusable-components.jsx

Created a mezzanine landing page to take the place of existing direct-to-app-creation CTA.

New CTA LP

---

src/components/pages/pricing/pricing-table/data/pricing-plans.js

Added new items to the `/pricing` page.

chore: add translations, hipaa

---

src/components/shared/reusable-sections/inbox/container/container.jsx
src/pages/index.jsx

This PR brings a minor fix to inbox background
<details>
<summary>Screenshots</summary>
Before:
After:
</details>

fix: inbox background

---

src/components/pages/pricing/pricing-table/data/pricing-plans.js

fix: update free tier ui workflow availability time

---

src/components/shared/cookie-banner/cookie-banner.jsx

This pull request fixes cookie-banner background.

feat: update background for cookie-banner

---

src/styles/fonts.css
tailwind.config.js

This pull request brings fallback font to prevent layout-shifting

fix: add fallback font to prevent layout-shift

---

src/components/pages/pricing/pricing-table/data/pricing-plans.js

Updated team member count for the business plan to align with the product change.

chore: update team member count on business plan

---

src/components/pages/community/get-involved/get-involved.jsx
src/components/pages/use-case/content/content.jsx
src/constants/links.js
src/data/pages/thank-you-discovery-session/get-involved.js
src/pages/inbox.jsx
src/pages/landing/get-started.jsx
src/pages/landing/react-email-blocks.jsx
src/pages/staging-pages/NEW-index.jsx
src/pages/testpages/reusable-components.jsx
src/pages/usecases/add-notifications.jsx
src/pages/usecases/content-management.jsx
src/pages/usecases/improve-communication-experience.jsx
src/pages/usecases/multi-channel-notifications.jsx
src/pages/usecases/unified-platform.jsx

Update links to point to new dashboard

chore: update v2 dashboard link

---

src/components/shared/header/header.jsx
src/components/shared/mobile-menu/mobile-menu.jsx
src/constants/links.js
src/constants/menus.js

The previous nav update did not have links for the new login button. This PR fixes that.

fix: re-add login link

---

src/constants/menus.js

Added the new security page link to the navbar, and moved around the footer links a bit.

chore: update links

---

src/constants/menus.js

Missed a comma. This PR fixes the resulting broken menu

fix: add comma

---

.husky/commit-msg
src/pages/index.jsx

This PR corrects the utm_campaign tags in the last CTA

chore: update utm

---

src/styles/global.css

Add smooth scroll to anchor links to whole website
**Steps to check:**
1. Open [preview](https://deploy-preview-312--novu-website.netlify.app/landing/get-started/#video)
2. Make sure that everything looks and works as expected

feat: add smooth scroll to the website

---

src/constants/menus.js

This pull request fixes broken link in header navigation

fix: fix broken link in header nav

---

src/components/shared/link-banner/link-banner.jsx
src/components/shared/link/link.jsx
src/components/shared/mobile-menu/mobile-menu.jsx
src/components/shared/mobile-menu/sub-menu/sub-menu.jsx
src/data/link-banner.js

Update top banner:
- New option to add `Read more` text
- Hide long text for small screens
**Steps to check:**
1. Open [preview](https://deploy-preview-324--novu-website.netlify.app)
2. Make sure that everything looks and works as expected

feat: update top banner
